function plotDegreeCentrality(SubNetProp, VarList)
%PLOTDEGREECENTRALITY it takes the output generated by subnetProperties function and
%generates plots
fullscreen = get(0,'ScreenSize');
figure('Position',[0 -50 fullscreen(3) fullscreen(4)], 'NumberTitle','off', 'Name', 'plot activities');
    subplot(3,2,6);
     plot(SubNetProp.deg(1,:),'LineWidth',5);
     set(gca, 'XTick', 1:length(SubNetProp.deg(1,:)), ...                            
    'XTickLabel', VarList);
    xtickangle(90)
    title('in degrees of neurons');
    hold on
    
    subplot(3,2,5);
    plot(SubNetProp.deg(2,:),'LineWidth',5);
    set(gca, 'XTick', 1:length(SubNetProp.deg(1,:)), ...                            
             'XTickLabel', VarList);
    xtickangle(90)
    title('Out degrees of neurons');
    hold on
    
    subplot(3,2,4)
    histogram(SubNetProp.deg(1,:));
    title('histogram in degrees of neurons');
    hold on
    
    subplot(3,2,3)
    histogram(SubNetProp.deg(2,:));
    title('histogram out degrees of neurons');
    hold on
end

