function pharynx = pharynx_connectivity
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/adrien/Documents/biophys-project/Analysis/Synapse2020.xlsx
%    Worksheet: herm gap jn synapse adjacency
%
% Auto-generated by MATLAB on 09-Jan-2021 18:08:35

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 57);

% Specify sheet and range
opts.Sheet = "herm gap jn synapse adjacency";
opts.DataRange = "D4:BH60";

% Specify column names and types
opts.VariableNames = ["I1L", "I1R", "I2L", "I2R", "I3", "I4", "I5", "I6", "M1", "M2L", "M2R", "M3L", "M3R", "M4", "M5", "MCL", "MCR", "MI", "NSML", "NSMR", "pm1", "pm2D", "pm2VL", "pm2VR", "pm3D", "pm3VL", "pm3VR", "pm4D", "pm4VL", "pm4VR", "pm5D", "pm5VL", "pm5VR", "pm6D", "pm6VL", "pm6VR", "pm7D", "pm7VL", "pm7VR", "pm9", "mc1DL", "mc1DR", "mc1V", "mc2DL", "mc2DR", "mc2V", "mc3DL", "mc3DR", "mc3V", "e2D", "e2VL", "e2VR", "e3D", "e3VL", "e3VR", "g1AL", "g1AR"];
opts.SelectedVariableNames = ["I1L", "I1R", "I2L", "I2R", "I3", "I4", "I5", "I6", "M1", "M2L", "M2R", "M3L", "M3R", "M4", "M5", "MCL", "MCR", "MI", "NSML", "NSMR", "pm1", "pm2D", "pm2VL", "pm2VR", "pm3D", "pm3VL", "pm3VR", "pm4D", "pm4VL", "pm4VR", "pm5D", "pm5VL", "pm5VR", "pm6D", "pm6VL", "pm6VR", "pm7D", "pm7VL", "pm7VR", "pm9", "mc1DL", "mc1DR", "mc1V", "mc2DL", "mc2DR", "mc2V", "mc3DL", "mc3DR", "mc3V", "e2D", "e2VL", "e2VR", "e3D", "e3VL", "e3VR", "g1AL", "g1AR"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
pharynx = readtable("/Users/adrien/Documents/biophys-project/Analysis/Synapse2020.xlsx", opts, "UseExcel", false);

%% Convert to output type
pharynx = table2array(pharynx);

%% Clear temporary variables
clear opts